// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock is a generated GoMock package.
package mock

import (
	model "github.com/codingXiang/backend-skeleton/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateDepartment mocks base method
func (m *MockService) CreateDepartment(data model.DepartmentInterface) (*model.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDepartment", data)
	ret0, _ := ret[0].(*model.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDepartment indicates an expected call of CreateDepartment
func (mr *MockServiceMockRecorder) CreateDepartment(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDepartment", reflect.TypeOf((*MockService)(nil).CreateDepartment), data)
}

// CreateUser mocks base method
func (m *MockService) CreateUser(data model.UserInterface) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", data)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser
func (mr *MockServiceMockRecorder) CreateUser(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockService)(nil).CreateUser), data)
}

// GetDepartmentList mocks base method
func (m *MockService) GetDepartmentList() ([]*model.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartmentList")
	ret0, _ := ret[0].([]*model.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartmentList indicates an expected call of GetDepartmentList
func (mr *MockServiceMockRecorder) GetDepartmentList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartmentList", reflect.TypeOf((*MockService)(nil).GetDepartmentList))
}

// GetDepartment mocks base method
func (m *MockService) GetDepartment(data model.DepartmentInterface) (*model.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartment", data)
	ret0, _ := ret[0].(*model.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartment indicates an expected call of GetDepartment
func (mr *MockServiceMockRecorder) GetDepartment(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartment", reflect.TypeOf((*MockService)(nil).GetDepartment), data)
}

// GetUserList mocks base method
func (m *MockService) GetUserList() ([]*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserList")
	ret0, _ := ret[0].([]*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserList indicates an expected call of GetUserList
func (mr *MockServiceMockRecorder) GetUserList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserList", reflect.TypeOf((*MockService)(nil).GetUserList))
}

// GetUser mocks base method
func (m *MockService) GetUser(data model.UserInterface) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", data)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser
func (mr *MockServiceMockRecorder) GetUser(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockService)(nil).GetUser), data)
}

// ModifyDepartment mocks base method
func (m *MockService) ModifyDepartment(data model.DepartmentInterface) (*model.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyDepartment", data)
	ret0, _ := ret[0].(*model.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModifyDepartment indicates an expected call of ModifyDepartment
func (mr *MockServiceMockRecorder) ModifyDepartment(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyDepartment", reflect.TypeOf((*MockService)(nil).ModifyDepartment), data)
}

// ModifyUser mocks base method
func (m *MockService) ModifyUser(data model.UserInterface) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyUser", data)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModifyUser indicates an expected call of ModifyUser
func (mr *MockServiceMockRecorder) ModifyUser(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyUser", reflect.TypeOf((*MockService)(nil).ModifyUser), data)
}

// DeleteDepartment mocks base method
func (m *MockService) DeleteDepartment(data model.DepartmentInterface) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDepartment", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDepartment indicates an expected call of DeleteDepartment
func (mr *MockServiceMockRecorder) DeleteDepartment(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDepartment", reflect.TypeOf((*MockService)(nil).DeleteDepartment), data)
}

// DeleteUser mocks base method
func (m *MockService) DeleteUser(data model.UserInterface) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser
func (mr *MockServiceMockRecorder) DeleteUser(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockService)(nil).DeleteUser), data)
}
