application:
  timeout:
    read: 1000
    write: 1000
  port: 8080
  mode: "test"
  log:
    level: "debug"
    format: "json"
  appId: "iam"
  appToken: ""
  apiBaseRoute: "/api"
i18n:
  defaultLanguage: "en"
  file:
    path: "/Users/user/go/src/backend-skeleton/i18n"
    type: "yaml"